### ISSUE TITLE
[BUG] UCI BusinessProcessFlow Lookup SetValue fails if the same attribute exists on the form and is set to read-only

### ISSUE THREAD

**Issue by vaclavrozsypal** [Microsoft/EasyRepro#819] opened 2020-04-01 20:16 UTC
**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [x] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [x] Online
  - [ ] On Premise

**Browser**
  - [x] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
BusinessProcessFlow Lookup SetValue fails if the same attribute exists on the form and is set by customization to read-only.

**Code to reproduce**  
```csharp
xrmApp.BusinessProcessFlow.SelectStage("stageName");
xrmApp.BusinessProcessFlow.SetValue(new LookupItem { Name = "attributeLogicalName", Value = "someValue", Index = 0 });

// fails here, when control in BPF is empty:
input.SendKeys(Keys.Control + "a");
```

**Comment by TYLEROL** [comment] 2020-05-20 22:48
@vaclavrozsypal - We've made some changes to SetValue() that should better handle the 'context' of which you are setting the field value.

These were merged today into both the releases/v9.1 branch and the 9.1.0.17138 NuGet package. Please re-open this accordingly if the issue is not resolved.

Warm Regards,
Tyler

**Closed as completed by TYLEROL** 2020-05-20 22:48 UTC
Labels: bug
