### ISSUE TITLE
Sales-Contact-Connection Not able to select or enter text

### ISSUE THREAD

**Issue by Nixlene** [Microsoft/EasyRepro#42] opened 2017-10-23 05:04 UTC
Hi Everyone,

      I am not able to enter text & select value in lookup field.
 Sales-Contact-Connection

error: {"no such element: Unable to locate element: {\"method\":\"class name\",\"selector\":\"ms-crm-Inline-Edit\"}\n  (Session info: chrome=61.0.3163.100)\n  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Windows NT 6.1.7601 SP1 x86_64)"}

    

              xrmBrowser.Navigation.OpenSubArea("Sales", "Contacts");
              xrmBrowser.Navigation.OpenRelated("Connections");
                
                xrmBrowser.Related.ClickCommand("Connect", "To Me", false, 500);
                          
                xrmBrowser.ThinkTime(1000);
                                
                xrmBrowser.Navigation.SwitchToPopupWindow();
                xrmBrowser.Navigation.SwitchToDefaultContent();
                xrmBrowser.Navigation.SwitchToContentFrame();

                xrmBrowser.Entity.SetValue("description", "test");

                xrmBrowser.Entity.SelectLookup("record2roleid", 6);
                xrmBrowser.Entity.Save();
               
                xrmBrowser.CommandBar.ClickCommand("Save & Close");

**Comment by dtu11** [comment] 2017-10-23 17:32
Ok, I'll test this scenario and see what the issue is.   More than likely the driver is on another frame and can't find the element.

**Comment by j621z** [comment] 2017-11-15 23:54
We are currently working on this issue and will provide an update soon.

**Comment by dtu11** [comment] 2017-12-04 02:47
This issue is fixed in the latest release.  Please test with the latest build and let us know if you run into any issues. 

Thanks

**Closed by dtu11** 2017-12-04 02:47 UTC
