### ISSUE TITLE
Lookup doesn't work in v9.1

### ISSUE THREAD

**Issue by SachchinAnnam** [Microsoft/EasyRepro#371] opened 2019-02-11 07:55 UTC
Hello @ggeiszle and @TYLEROL
I tried below snippet for lookup but it didn't worked:
xrmApp.Entity.SetValue({ Name = "language", Value = "English"});
Even SelectLookup isn't helping.
xrmApp.Entity.SelectLookup("language");

Where **language** is the field name.
Please help with some options.

**Comment by dnamrgrts** [comment] 2019-02-11 14:21
Hello, 
xrmApp.Entity.SelectLookup(string field, int index);  
For Example-> xrmApp.Entity.SelectLookup("language", 0); 
select the first record of your Look up

**Comment by SachchinAnnam** [comment] 2019-02-11 15:03
Hello @dnamrgrts  
It give error as 'No overload for method 'SelectLookup' takes 2 arguments	'

**Comment by SachchinAnnam** [comment] 2019-02-11 15:53
I modified my scripts:


                LookupItem language = new LookupItem { Name = "language", Value = "English" };
                xrmApp.Entity.SetValue(language);
              // **Above snippet works**

                LookupItem country = new LookupItem { Name = "im360_countryid", Value = "Brazil" };
                xrmApp.Entity.SetValue(country);
            // **Above snippet works**
                
                //xrmApp.ThinkTime(2000);
                LookupItem parentID = new LookupItem { Name = "parentcustomerid", Value = "LARSEN & TOUBRO INFOTECH LIMITED" };
                xrmApp.Entity.SetValue(parentID); // as per below exception - it fails on this line
            // **Above snippet doesn't work**

Here is the exception 
Test Name:	UCITestCreateContact
Test FullName:	Microsoft.Dynamics365.UIAutomation.Sample.UCI.CreateContactUCI.UCITestCreateContact
Test Source:	D:\EasyRepro\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Sample\UCI\Create\CreateContact.cs : line 22
Test Outcome:	Failed
Test Duration:	0:01:15.7415573

Result StackTrace:	
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Click()
   at Microsoft.Dynamics365.UIAutomation.Browser.SeleniumExtensions.Click(IWebElement element, Boolean ignoreStaleElementException) in D:\EasyRepro\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Browser\Extensions\SeleniumExtensions.cs:line 41
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass61_0.<SetValue>b__0(IWebDriver driver) in D:\EasyRepro\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 1587
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params) in D:\EasyRepro\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Browser\DelegateBrowserCommand.cs:line 28
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9) in D:\EasyRepro\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 136
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute(IWebDriver driver) in D:\EasyRepro\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Browser\BrowserCommand.cs:line 36
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate) in D:\EasyRepro\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Browser\BrowserPage.cs:line 182
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.SetValue(LookupItem control, Int32 index) in D:\EasyRepro\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Api.UCI\WebClient.cs:line 1567
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.Entity.SetValue(LookupItem control, Int32 index) in D:\EasyRepro\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Api.UCI\Elements\Entity.cs:line 302
   at Microsoft.Dynamics365.UIAutomation.Sample.UCI.CreateContactUCI.UCITestCreateContact() in D:\EasyRepro\EasyRepro-releases-v9.1\Microsoft.Dynamics365.UIAutomation.Sample\UCI\Create\CreateContact.cs:line 47
Result Message:	
Test method Microsoft.Dynamics365.UIAutomation.Sample.UCI.CreateContactUCI.UCITestCreateContact threw exception: 
System.InvalidOperationException: unknown error: Element <input id="id-a6f52357-a4a2-4a89-a4ec-d7f9b6d6b61b-5-parentcustomerid-parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_0_textInputBox_with_filter_new" aria-label="Company  Lookup" aria-required="true" data-id="parentcustomerid.fieldControl-LookupResultsDropdown_parentcustomerid_textInputBox_with_filter_new" title="" placeholder="" maxlength="200" autocomplete="off" aria-multiline="false" aria-autocomplete="list" type="text" class="n uv io ip jz jy dp fc tt uw ux uy uz va vb vc vd ve on " value="---" aria-haspopup="true"> is not clickable at point (346, 64). Other element would receive the click: <span aria-label="..." tabindex="-1" class="fc cx gh ar e ax gi bv ">New</span>
  (Session info: chrome=72.0.3626.96)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.16299 x86_64)

**Comment by nlipkow** [comment] 2019-02-13 09:31
I'm running into similar issues here:
```
LookupItem item = new LookupItem { Name = "pricelevelid", Value = "de_sales_2016"};
xrmBrowser.Entity.SetValue(item);
xrmBrowser.ThinkTime(2000);

LookupItem item = new LookupItem { Name = "customerid", Value = "Nancy Anderson (sample)"};
xrmBrowser.Entity.SetValue(item);
```
The first instruction to set the value for "pricelevelid" works perfectly fine. The second however fails and I get the following exception: 
`System.InvalidOperationException: List does not contain a record with the name:  Nancy Anderson (sample)`

The image below though indicates that it does exist. I had for some reason also some undeterministic behaviour while debugging through this error and had the value "Nancy Anderson (sample)" accepted before but could not reproduce it. Maybe this is related to some sort of race condition between the WebClient and the query?

I'm also on the current branch `releases/v9.1`
![image](https://user-images.githubusercontent.com/20375505/52700668-cd646300-2f78-11e9-99ea-739980704868.png)

**Comment by SachchinAnnam** [comment] 2019-02-21 10:42
@TYLEROL : Please help us with any workarounds as we are stuck with this lookup.

**Comment by markcunninghamuk** [comment] 2019-03-04 19:21
Any updates on this, not working for us either

**Comment by SachchinAnnam** [comment] 2019-04-10 18:32
Hello @TYLEROL 
Any workaround for this bug?

Appreciate your assistance on this.

**Comment by markcunninghamuk** [comment] 2019-04-10 21:03
There is a workaround I added called highlight record. You can then use the 'edit command after it is selected.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SachchinAnnam** [comment] 2019-04-12 19:09
@markcunninghamuk: is your workaround related to selecting Account from lookup field?

**Comment by BillOwens** [comment] 2019-04-18 18:56
I am having the same issue. Are there any updates as we are stuck now,

**Comment by BillOwens** [comment] 2019-04-22 15:41
I was able to get my test to work. I added a ThinkTime afterwards and it worked. I beleive we are just not giving the control enough time to fully function.
```
LookupItem contact = new LookupItem { Name = "primarycontactid", Value = "User, UITesting" };
xrmApp.Entity.SetValue(contact);
xrmApp.ThinkTime(3000);

```

**Comment by ghost** [comment] 2019-04-23 14:10
i trying this in the V9.1 but Unified Interface doesn´t work... anyone with the same problem?

**Comment by markcunninghamuk** [comment] 2019-04-24 05:29
William Owens is correct. It is much more reliable with a thinktime added.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SachchinAnnam** [comment] 2019-04-25 07:36
It works well, when the lookup has relatively small number of items.. Like while selecting Language or Currency.
But it fails with the below error when we try to select Account where lookup has large number of items.
_List does not contain a record with the name:  **abc_AccountName**_

**Comment by silverbrewer07** [comment] 2019-05-02 12:17
I am also having this issue. I agree with Sachin it works great when you have a small list. The more frustrating issue for me is it was working fine and just stopped working - guess it could be as we have added more records. The more frustrating part is if you debug the test and get the error and continue it ends up setting the value. This has us stopped in automated testing in the UI. 

Thanks!!

**Comment by silverbrewer07** [comment] 2019-05-03 03:30
After some additional testing it actually types the field and the option is displayed in the lookup box but it just doesn't get selected. I have as a temporary work around just used javascript to set the field values but it does not support any conditional testing. This issue has gotten much worse since the latest update in UCI

**Comment by SachchinAnnam** [comment] 2019-05-03 06:31
Do we have any workaround as we are stuck with lookup selection in almost all the scripts?
@TYLEROL : Please help us.

**Comment by GowriRamanujapu** [comment] 2019-05-07 08:53
I am having the same issue. Not able to select a value from look up . CRM FS version is 8.6.0.274

**Comment by SachchinAnnam** [comment] 2019-05-09 10:09
Do we have any updates, as most of us are facing the same issue and not able to proceed further due to the underline issue.

**Comment by jlattimer** [comment] 2019-05-15 00:36
@nlipkow your issue might be because of the way the lookup is set using XrmBrowser. Currently the behavior will open the dialog with the top X results and then attempt to do a case sensitive match on the results. So if Price Level only has a few values, it stands to reason it would be in the list of what is initially displayed before a search. In the case of the Contact lookup, is Nancy Anderson isn't in the initial list of records it will fail with the error you're seeing.  Submitted [PR 479](https://github.com/microsoft/EasyRepro/pull/479) for this.

**Comment by jlattimer** [comment] 2019-05-21 00:25
Merged into 9.1 branch - closing

**Closed as completed by jlattimer** 2019-05-21 00:25 UTC
Labels: bug

**Comment by sathya-devi** [comment] 2019-05-30 07:41
@TYLEROL  @jlattimer I am facing issues in these type of look up field for Contact and Account, Other Lookups(Country) are working. I tried with Current release v9.1. 

![image](https://user-images.githubusercontent.com/48006128/58616825-43989580-82dc-11e9-83c0-cc0ee9453f5f.png)

**Comment by jlattimer** [comment] 2019-05-30 14:05
Pull request [515](https://github.com/microsoft/EasyRepro/pull/515) adds the ability to use activity party fields

**Comment by ArvindBhat83** [comment] 2019-06-19 11:06
I still don't see it working while creating cases in UCI.  It doesn't set the lookup but the test case execution says it was successful

**Comment by rahiltg** [comment] 2020-02-06 08:31
> I still don't see it working while creating cases in UCI. It doesn't set the lookup but the test case execution says it was successful

I agree as i am also facing the same problem. I have created a bug with more details.
https://github.com/microsoft/EasyRepro/issues/750

**Comment by swethagampala** [comment] 2020-05-22 05:56
Hello. I cloned latest v9.1 version. I still see this error:
Message: Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount threw exception: 
System.InvalidOperationException: Login page failed
I am using IE. It logs in with username, password and IE ask to remember dialog and then test fails.
I added this line also: 

 xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
                xrmBrowser.GuidedHelp.CloseGuidedHelp();
                xrmBrowser.Dialogs.CloseWarningDialog();
                **xrmBrowser.Navigation.OpenApp("Sales Hub");**
                xrmBrowser.ThinkTime(500);
                xrmBrowser.Navigation.OpenSubArea("Sales", "Accounts");

Please help. I am on version 9.1.x sandbox.
