### ISSUE TITLE
How to Change Form/View on Entity

### ISSUE THREAD

**Issue by trentet** [Microsoft/EasyRepro#56] opened 2017-12-11 18:04 UTC
I apologize if there is a better place to ask questions like this, if there is, please let me know.

Is there already functionality in EasyRepro for checking and/or changing the form/view for an Entity? I'm having a problem where some entities default to a form/view that is different than the one I'm wanting to test, and I am not sure how to go about changing that. I'm familiar with using Grid.SwitchView(), but I can't find an equivalent method for Entities.

Note: I am not referring to the Form dropdown directly to the right of the Entity name. I am referring to the dropdown directly above the entity name.

**Comment by dtu11** [comment] 2017-12-11 22:05
Which version are you using?  Can you send a screenshot of what you're referring too?  Here is the view in my org that we're using for testing.   The menu to the right of the Account name is to select the section.  The dropdown for the entity is the form.  

![image](https://user-images.githubusercontent.com/26821561/33856229-176b2f1c-de8d-11e7-80c3-d6743b2e2005.png)

**Comment by trentet** [comment] 2017-12-11 22:36
v8.2. 

![image](https://user-images.githubusercontent.com/24260409/33857363-86cec896-de88-11e7-9499-efa5fb6bfb95.png)

I want to be able to open the dropdown above the entity name and select from the dropdown list. I've made some progress making my own solution, but it's probably low quality in comparison to an official solution.

If I use the SelectForm method, it opens the area you have encircled with blue in that image.

**Comment by dtu11** [comment] 2017-12-11 22:42
We're looking at this issue for Issue #54.  I'll expand the version to include v8.2

**Comment by j621z** [comment] 2017-12-18 19:41
@trentfromrid Please try something like this. Set the "formSection" var to the name of the section within the form you'd like to change. 
```
public void TestOpenLeadSwitchForms()
        {
            using (var xrmBrowser = new XrmBrowser(TestSettings.Options))
            {
                xrmBrowser.LoginPage.Login(_xrmUri, _username, _password);
                xrmBrowser.GuidedHelp.CloseGuidedHelp();

                xrmBrowser.ThinkTime(500);
                xrmBrowser.Navigation.OpenSubArea("Sales", "Accounts");

                xrmBrowser.Grid.OpenRecord(0);

                xrmBrowser.ThinkTime(1000);

                var formSection = "Details";
                xrmBrowser.Entity.SelectForm(formSection, 1000);

                form = "Summary";
                xrmBrowser.Entity.SelectForm(formSection, 1000);

            }
        }
```

**Comment by steveplatz** [comment] 2018-02-19 20:14
@trentet I had to do something similar and noticed the functionality hasn't been added yet. I wrote up the following extension class to to pull off form switching for 8.2. I'm sure it can be improved in one way or another, but it seems to do the trick for me.

    public static class XrmBrowserExtensions
    {
        public static BrowserCommandResult<bool> SwitchForm(this XrmBrowser This, string formName)
        {
            var browserCommandOptions = new BrowserCommandOptions(
                Constants.DefaultTraceSource,
                $"Open Form: {formName}",
                0,
                0,
                null,
                true,
                typeof(NoSuchElementException),
                typeof(StaleElementReferenceException));

            return This.Document.Execute(browserCommandOptions, driver =>
            {
                SwitchFormCommand(This, formName);
                return true;
            });
        }

        private static bool SwitchFormCommand(XrmBrowser browser, string formName)
        {
            if (string.IsNullOrEmpty(formName))
                throw new ArgumentNullException("Form name not specified");

            browser.Document.SwitchToContentFrame();

            // Expand the form selector to load the possible options
            var formSelector = browser.Document.getElementById("header_crmFormSelector");
            formSelector.Click();

            // Find the menu option matching the specified name
            var menuOption = browser.Document.getElementByXPath($"//div[@class='ms-crm-FS-Menu']//a[@title='{formName}']");
            if (menuOption != null)
            {
                menuOption.Click();
            }
            else
            {
                return false;
            }

            browser.Driver.WaitForPageToLoad();

            return true;
        }
    }

You can call this by by doing the following:

    [TestMethod]
    public void MyTest()
    {
        using (var xrmBrowser = new XrmBrowser(TestSettings.Options))
        {
            xrmBrowser.SwitchForm("Form Name");
        }
    }

**Comment by TYLEROL** [comment] 2018-03-02 23:39
Thanks @steveplatz for helping out here!

@trentet - We've confirmed this same behavior and SelectForm is not working as intended. I'll work with our team to get an update posted soon. Once the fix is available I'll confirm here.

-Tyler

**Comment by TYLEROL** [comment] 2018-05-01 17:25
@trentet - With the latest release of EasyRepro, this issue has been corrected. The Entity.SelectForm() method should adjust the form you want, while a new Entity.SelectFormSection() method has been added to allow interaction with the form section drop down.

I'll close this issue as resolved, however please don't hesitate to update us if you have questions and/or issues with the latest code.

Regards,
Tyler

**Closed as completed by TYLEROL** 2018-05-01 17:25 UTC
Labels: bug
