### ISSUE TITLE
[BUG] SetValue for LookupItem failing with Object reference not set exception

### ISSUE THREAD

**Issue by easyrepro** [microsoft/EasyRepro#721] opened 2020-01-17 23:56 UTC
## Bug Report

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [x] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [ ] UCI (XrmApp)
  - [x] Classic Web (XrmBrowser)

**Online or On Premise**
  - [x] Online
  - [ ] On Premise

**Browser**
  - [x] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  
SetValue for LookupItem failing with error due to lack of proper waiting for dialog element. Some times 
 ```csharp
var dialog = driver.WaitUntilAvailable(By.Id(dialogName));
```
is returning null and due to which 
```csharp
OpenDialog(dialog).Value
```
is failing with "Object reference not set to an instance of object" exception.

**Special formatting / display**  

**Code to reproduce**  
 ```csharp
xrmBrowser.Entity.SetValue(new LookupItem() { Name = "fieldId", Value = "testValue" }) ;
```
**Expected behavior**  
Should select lookup value without exception even when loading of dialog is delayed

**Additional context**  
Adding Browser.ThinkTime before
 ```csharp
var dialogName = $"Dialog_{control.Name}_IMenu";
```
solved issue. 
Similarly adding Browser.ThinkTime before
 ```csharp
SwitchToDialog();
driver.WaitUntilAvailable(By.XPath(Elements.Xpath[Reference.Grid.FindCriteria]));
```
solved Lookup dialog waiting issue

**Comment by AngelRodriguez8008** [comment] 2020-01-20 07:36
Can be related to my comment in #707, please check it. 
WaitUntilAvailable is not working properly in that version.

**Comment by easyrepro** [comment] 2020-01-21 20:15
> Can be related to my comment in #707, please check it.
> WaitUntilAvailable is not working properly in that version.

Thanks @AngelRodriguez8008  Yes, it seems WaitUntilAvailable is not waiting for Dialog element to be visible and returning null

**Comment by KhoaAN** [comment] 2020-02-02 10:17
I know this issue was raised for D365 classic web not UCI but theres also a D365 problem with setting lookup value through the UI that started happening about 2 or 3 weeks ago (maybe through the last D365 update). Basically whenever a user started a new session and try to find the matching value from the Lookup field (by putting in text search value) on a form, it wouldn't be able to find the matching record. This issue has caused many of my tests to fail and in my case its the owner field on the form allowing user to search for a user or a team. This lookup field has a big number of records to search for. After failing to search for the first time, it will work fine if you try again after roughly 7 seconds. 
It looked like the control tried to cache the lookup data or something during the first usage. This issue needs to be fixed by Microsoft D365 team. On easyrepro side, it will just throw an error quickly after it hit the ".Search" method.
Screenshot showing the first time searching for matching records of D365 **owner** field (its just stuck there like that when you search for the first time):
![image](https://user-images.githubusercontent.com/19439727/73606416-2308a400-45fe-11ea-9947-f2763be63541.png)

This one shows the second try (after 5 to 7 secs):
![image](https://user-images.githubusercontent.com/19439727/73606708-5e58a200-4601-11ea-9559-720f4f234f69.png)

**Comment by KhoaAN** [comment] 2020-02-03 12:17
> I know this issue was raised for D365 classic web not UCI but theres also a D365 problem with setting lookup value through the UI that started happening about 2 or 3 weeks ago (maybe through the last D365 update). Basically whenever a user started a new session and try to find the matching value from the Lookup field (by putting in text search value) on a form, it wouldn't be able to find the matching record. This issue has caused many of my tests to fail and in my case its the owner field on the form allowing user to search for a user or a team. This lookup field has a big number of records to search for. After failing to search for the first time, it will work fine if you try again after roughly 7 seconds.
> It looked like the control tried to cache the lookup data or something during the first usage. This issue needs to be fixed by Microsoft D365 team. On easyrepro side, it will just throw an error quickly after it hit the ".Search" method.
> Screenshot showing the first time searching for matching records of D365 **owner** field (its just stuck there like that when you search for the first time):
> ![image](https://user-images.githubusercontent.com/19439727/73606416-2308a400-45fe-11ea-9947-f2763be63541.png)
> 
> This one shows the second try (after 5 to 7 secs):
> ![image](https://user-images.githubusercontent.com/19439727/73606708-5e58a200-4601-11ea-9559-720f4f234f69.png)

I discovered that our **ownerid** field isn't returning teams for the 1st time usage. It only returns users for the 1st search. Any searches after that would return both teams and users. Not sure if this issue was caused by our security roles setup and such or its a D365 bug from Microsoft.
1st search (by clicking on the field and hit Enter key):
![image](https://user-images.githubusercontent.com/19439727/73652433-10b06800-46db-11ea-9779-bfd2e1cc3687.png)

2nd search (by clicking on the field and hit Enter key):
![image](https://user-images.githubusercontent.com/19439727/73652532-41909d00-46db-11ea-8ecd-e1a56fe4fec6.png)

**Closed** 2020-02-06 21:22 UTC
Labels: bug
