### ISSUE TITLE
V9.1 WebClient.FilterWith Method is not functioning as intended

### ISSUE THREAD

**Issue by Bala-Ramadoss** [Microsoft/EasyRepro#507] opened 2019-05-23 12:48 UTC
WebClient.FilterWith method is not working as intended, it throws an exception even though GlobalSearch(Relevance Search) results have been successfully displayed.

We are unable to drill down the global search results as per the record type (refer to the highlighted part in screenshots attached).

The stack trace & others details are attached.

Class: Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient

**_NOTE :_** Also Request you to please provide a method exposed through API which can facilitate us to iterate through the global search results & retrieve all the attributes related to every record displayed in the global search results.

Stack Trace:

System.InvalidOperationException
  HResult=0x80131509
  Message=Filter With picklist is not available
  Source=Microsoft.Dynamics365.UIAutomation.Api.UCI
  StackTrace:
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.<>c__DisplayClass119_0.<FilterWith>b__0(IWebDriver driver)
   at Microsoft.Dynamics365.UIAutomation.Browser.DelegateBrowserCommand`1.ExecuteCommand(IWebDriver driver, Object[] params)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserCommand`1.Execute[T1,T2,T3,T4,T5,T6,T7,T8,T9](IWebDriver driver, T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6, T7 p7, T8 p8, T9 p9)
   at Microsoft.Dynamics365.UIAutomation.Browser.BrowserPage.Execute[TResult](BrowserCommandOptions options, Func`2 delegate)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.WebClient.FilterWith(String entity, Int32 thinkTime)
   at Microsoft.Dynamics365.UIAutomation.Api.UCI.GlobalSearch.FilterWith(String entity)

Screenshot:

image

**Comment by Bala-Ramadoss** [comment] 2019-05-31 09:41
waiting for a resolution on this issue. Please let know

**Comment by Bala-Ramadoss** [comment] 2019-06-04 14:32
@tylerol - Any updates on the fix for this issue. Eagerly waiting. Please let know.

**Comment by dtu11** [comment] 2019-06-05 23:23
I just tested in my test environment, that is version v9.1.0000.5035, and everything worked fine.   The method does a HasElement check looking for the picklist and then throws that exception if iit doesn't exist.   The previous action may not be completed yet and the picklist may not be rendered when the check occurs.    

I've modified the method to wait up to 10 seconds before throwing an exception.  It will check every 250ms for the picklist to be visible and then continue on when it's available.

**Comment by TYLEROL** [comment] 2019-06-06 00:11
@Bala-Ramadoss - Sorry for the delay on this. My colleague just submitted a PR which I've merged into the _develop_ branch.

I'm hoping to do a merge into releases/v9.1 by end of week with some additional fixes, however if you're able - could you kindly try pulling the develop branch and see if this resolves your test scenario? If so, I'll update once we've merged the fix into releases/v9.1.

Warm Regards,
Tyler

**Comment by Bala-Ramadoss** [comment] 2019-06-06 06:17
![FilterWith](https://user-images.githubusercontent.com/50577926/59010910-903a1e80-8850-11e9-91a9-b6ca91e85151.png)

The Highilghted area in the above attached screenhsot shows is where we are trying to filter or drill down the search results displayed due to the Global Search(Relevance Search). Expecting a resolution on this lines.

Thank You Team.

**Comment by Bala-Ramadoss** [comment] 2019-06-06 06:17
@TYLEROL @dtu11 & team - Please refer to above comment

**Comment by dtu11** [comment] 2019-06-06 14:57
Ok, the FilterWith was intended for Categorized Search.  I've changed this from a bug to an enhancement as this method was not intended to work with Relevance Search.     I'll see if I can add the appropriate API's to allow you to filter in Relevance.

**Comment by dtu11** [comment] 2019-06-10 14:17
Closing this issue.  If the fix doesn't address your problem please reopen.

**Closed as completed** 2019-06-10 14:16 UTC
Labels: enhancement

**Comment by Bala-Ramadoss** [comment] 2019-06-13 11:59
@dtull @tylerol - What is the link to the enhancement[issue number]? Please let know on the status of adding a appropriate API to perform filtering & iterate through search results of relevance search

**Comment by TYLEROL** [comment] 2019-06-14 13:43
Hi @Bala-Ramadoss ,

The fix is in PR #546 . This added the following changes:
 
> ChangeSearchType
> Filter
> GlobalRelevanceSearchTest
> Updated the following API's
> Updated GlobalSearch to handle both search types
> Updated OpenRecord to handle both search types

Please see the new test sample, UCITestGlobalRelevanceSearch, made available last night via the latest changes in releases/v9.1 branch - or via the 9.1.0.5229 NuGet package.

If you have any issues with these changes, please raise new issues as required.

Warm Regards,
Tyler
