### ISSUE TITLE
OpenQA.Selenium.WebDriverException   HResult=0x80131500   Message=javascript error: Cannot read property 'isAppIdle' of undefined

### ISSUE THREAD

**Issue by aalokkhare** [Microsoft/EasyRepro#685] opened 2019-11-28 15:26 UTC
## Bug Report
OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=javascript error: Cannot read property 'isAppIdle' of undefined
  (Session info: chrome=78.0.3904.108)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScript(String script, Object[] args)

### [Not covered](https://github.com/microsoft/EasyRepro#crm-functionality-not-covered) functionality, feature requests, and questions should use the Feature Request or Question templates.

**EasyRepro Version**
  - [ ] Microsoft Dynamics 365 Online Version 8.2 (8.2.x) (DB 8.2.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0 (9.0.x) (DB 9.0.x) online
  - [ ] Microsoft Dynamics 365 Online Version 9.0.2 (9.0.2) (DB 9.0.2) online
  - [ ] Microsoft Dynamics 365 Online Version 9.1 (9.1.x) (DB 9.1.x) online
  
**UCI or Classic Web**
  - [ * ] UCI (XrmApp)
  - [ ] Classic Web (XrmBrowser)

**Online or On Premise**
  - [ ] Online
  - [* ] On Premise

**Browser**
  - [ *] Chrome
  - [ ] Firefox
  - [ ] IE
  - [ ] Edge

**Describe the bug**  

**Special formatting / display**  

**Code to reproduce**  

 
**Expected behavior**  

**Screenshots**  

**Additional context**  
Dynamics 365 do not have browser library opening.

**Comment by dtu11** [comment] 2019-12-02 16:20
We are investigating this internally and working to get a fix asap.

**Comment by mhuguet** [comment] 2019-12-02 23:15
Duplicate of #683 
Apologies to all. A dependent client side API was removed by our peers. It has been added back and we are working on deploying globally. I'll update #683 once it starts rolling out with the plan.

**Closed as completed by mhuguet** 2019-12-02 23:15 UTC
Labels: bug, duplicate
