### ISSUE TITLE
grid.OpenRecord does not work as intended

### ISSUE THREAD

**Issue by mtremblay-savard** [Microsoft/EasyRepro#123] opened 2018-05-18 13:44 UTC
Hi,

The command to open a record does not work correctly, instead of opening a record, it clicks on "select all" and then crashes because the record never opens.

**Comment by mtremblay-savard** [comment] 2018-05-18 14:47
The problem comes from this part:
![image](https://user-images.githubusercontent.com/10708900/40241311-b13fa9fc-5a88-11e8-857a-281b8137c01f.png)
The blankSpans include the checkbox on the left but it always points to the first one, the select all, no matter which index you specify. To fix it, you could exclude the checkbox from the list to click on any other span, or simply always double click directly on the row.

**Comment by TYLEROL** [comment] 2018-05-18 16:44
Thanks @mtremblay-savard for raising this and for your investigation analysis.

The team member that wrote this did so in a manner because the initial implementation of DoubleClick() was opening the wrong record type in certain scenarios. The DoubleClick() method was targeting the middle of the grid, which was problematic if the middle of the grid view contained a Lookup field to a different record type. 

No issues were replicated across 8.2, 9.0, and 9.0.2 branches after implementing the blankSpan approach. This leads me to a few initial questions:

1. Which branch are you using? (v8.2, v9, v9.0.2)?
2. Which Dynamics 365 organization version are you testing against?
3. Selenium WebDriver version + Browser Version (should be included in exception details)
4. If able, provide a snippet of the page source when looking at the grid?

The OpenRecord() method should be targeting the _databodycontainer_ which contains the table data, as opposed to the _bodycontainer_ which is the fixed row containing the field headers and the Select All button.

![image](https://user-images.githubusercontent.com/29415524/40246840-243ad80a-5a7f-11e8-82c2-09133ef07c7b.png)

I'll try testing this further internally to see if we can try to replicate it, but on an out of box 9.0.2 organization this morning it functions as expected. I've included a screenshot below with view of the grid and data/fields it contains.

![image](https://user-images.githubusercontent.com/29415524/40246768-d64c3af8-5a7e-11e8-9a66-98d43faa23b3.png)



Regards,
Tyler

**Comment by mtremblay-savard** [comment] 2018-05-18 17:22
I'm using the branch v9.0 with CRM 8.2, maybe I should be using v8.2, i'll give it a try

**Comment by mtremblay-savard** [comment] 2018-05-18 18:03
Even when using 8.2 with my CRM 8.2 I get the same issue. I do have the same html setup as you:
![image](https://user-images.githubusercontent.com/10708900/40250370-0bfa13e4-5aa4-11e8-962b-52454ec8358f.png)

I've made some watchpoint to show you that all of their Checkboxes actually point to the same:
![image](https://user-images.githubusercontent.com/10708900/40250404-2bee7bf4-5aa4-11e8-92a9-84abdabf0e87.png)
You can see that for different rows, they all point to the same checkbox which is the select all at the top

**Comment by markleavesley** [comment] 2018-06-18 16:30
I am also having this problem. I found that "driver.DoubleClick(links[index]);" works fine. I'm fairly new to this but this is what I am doing:

Login
Go to a sub-area
Search the grid (Grid.Search), returns one result
Open record 0 (Grid.OpenRecord)

I'm using EasyRepro as downloaded from GitHub today with the latest Selenium nugets, my CRM is 8.2.

**Comment by TYLEROL** [comment] 2018-09-28 16:16
@mtremblay-savard and @markleavesley - We're taking another look at this issue.

We still have not been able to reproduce the exact issue described, however I have observed in my "no repro" scenarios that Grid.OpenRecord({recordIndex}) is not opening the expected record. I have replicated this across IE, Edge, and Chrome. It's possible this is related, since it's ultimately an incorrect target being selected.


I'll update once a fix is made available, and have you re-test your scenarios at that time. Thanks for your patience while we continue to work through this.


Best Regards,
Tyler

**Comment by TYLEROL** [comment] 2018-09-28 22:54
@mtremblay-savard and @markleavesley 

We've pushed an update via the beta/9.0.2 branch to adjust how the Grid.OpenRecord() method works. The new change will instead identify the available links in the data table, and attempt to double click the first data position in the row, the checkbox. This will replace the prior code looking for empty spans to click.

This new code resolved the issue I observed in which the OpenRecord method would open the incorrect row from the grid. We hope this will take care of the issues you observed as well.

I'll close this for now based on the PR fix - however if you continue to have problems please re-open, update the issue and we'll take another look.

**Note: I tested this fix on both 8.2.2 and 9.0.2 builds using the beta/9.0.2 branch. We can work to backport this change to other branches as required if this resolves your issue.**

Best Regards,
Tyler

**Closed as completed by TYLEROL** 2018-09-28 22:54 UTC
Labels: bug
