### ISSUE TITLE
not clickable

### ISSUE THREAD

**Issue by rijat** [Microsoft/EasyRepro#179] opened 2018-09-04 07:37 UTC
Hi guys;

why it's not clickable?

Test method Microsoft.Dynamics365.UIAutomation.Sample.Web.CreateAccount.WEBTestCreateNewAccount threw exception:
System.InvalidOperationException: unknown error: Element ... is not clickable at point (319, 25). Other element would receive the click:
...

(Session info: chrome=68.0.3440.106)
(Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Windows NT 10.0.17134 x86_64)

**Comment by TYLEROL** [comment] 2018-09-25 01:02
Hi @rijat , this appears to be a duplicate of issue you posted in #175. We'll close this as a duplicate and review that issue. If this is NOT a duplicate, please re-open as required.

Best Regards,
Tyler

**Closed as completed by TYLEROL** 2018-09-25 01:02 UTC
Labels: duplicate
